query_module_inventory:
  name: Query module inventory
  description: Trigger a Nikobus module inventory.
  fields:
    module_address:
      name: Module address
      description: "Module address to query. Leave empty to scan all modules."
      example: "05FA"
      required: false
      selector:
        text:
